trigger:
  - dev/main

# 2. Conectamos tu repositorio de infraestructura/gobernanza de Azure
resources:
  repositories:
    - repository: repo-gobernanza
      type: git
      name: azure-voting-app # Tu repositorio en Azure DevOps

# 3. Llamamos de forma segura a tu archivo centralizado
jobs:
  - template: github-trigger.yml@repo-gobernanza
